### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by ghost**
Hi. I've finished the translation. It's very close to the original English version, but I have:

- reorganised the sections a bit to in a more logical way (I shall apply the same to the English version in the future, which will show and explain the details),
- updated some parts (which I shall apply to the English version too),
- corrected some errors, or so I thought. This in particular will have to be applied to the English version.

I need some time to collect all the changes and improvements and work on the original English version. I've found some linguistic errors too.

As for the technical errors I fixed, recounting from memory, the description of delta graphs is faulty and the reference locations for relative links in the descriptions of AQ (the config file) and Leela Zero (weights file) are not correct. Those links, **I guess**, should be relative to the working location as shown by `pwd`, and not to the executive file's location. This may be different, but I'm sure the current description is not correct, at least as regards Leela Zero's weights.

Pull if you agree. Thanks.

### CODE REVIEW

**Comment by pnprog** [comment]
Hi!
I will check carefully this weekend, but one comment for this points:

> the reference locations for relative links in the descriptions of AQ (the config file) and Leela Zero )weights file) are not correct. Those links, I guess, should be relative to the working location as shown by pwd, and not to the executive file's location. 

In fact, for AQ, LeelaZero and PhoenixGo, GRP launches them in their own working directory, to make it easier for users, as they most probably put the weights and config file in that place.

[https://github.com/pnprog/goreviewpartner/blob/3c5cbaa713352c9a115a6400666b7433c0232dca/aq_analysis.py#L145](https://github.com/pnprog/goreviewpartner/blob/3c5cbaa713352c9a115a6400666b7433c0232dca/aq_analysis.py#L145)

It makes no change for GnuGo and Leela, and Pachi seems to change the cwd by itself.

**Comment by ghost** [comment]
Two lines later there's the `else` branch, which must be my case, as I have `leelaz` on my PATH and just call it that way. Then the analysis script inherits cwd from the main process, which in turn inherits it from the calling shell. Hence the discrepancy. So it should be correct, but only when the bot is called with a directory. (I guess, I've not tested, but assume that's how you run it.)

**Comment by ghost** [comment]
The last commit b86bf38 concerns the Polish translation only. I'd merge all the Polish commits and the HTML build instructions, but there's the English doc commit 254281f on the merge list, which I'm not sure what to do with. (That's just linguistic and presentation fixes, so it could be merged to. But I don't want to be to bossy here, so I'm leaving it with you.)

**Comment by pnprog** [comment]
Hi!
Thanks again for the work! Sorry, I have been a bit busy lately.

> I have leelaz on my PATH

I did not think about about this situation in fact, so I should have a try to see what is GRP behaviour in this case.

> (That's just linguistic and presentation fixes, so it could be merged to. But I don't want to be to bossy here, so I'm leaving it with you.)

Haha, don't even worry about this, just go ahead with the modifications. It's better to "release soon" and fix later, and in the case of documentation, it would be probably harmless :)

**Comment by pnprog** [comment]
I just had a look at my code, so apparently, when Leelaz is ran from PATH, then yes Leelaz is ran without indication of working directory, then is ran probably from GRP directory or whatever the shell provides.

But then, with LeelaZero on your path, you always provide the weight files with absolute location?

For other bot it depends:

- I am pretty sure AQ won't work this way (need to reboot on windows to try), because it expects to find some other files (like **prob_ptn12.txt** and others) inside the working directory. So for AQ, launching it within its folder is best
- Leela, Ray and Gnugo don't care apparently
- Pachi on windows does not care (it seems it change the working directory by itself) but needs the correct working directory for Linux

So I think we should advise to always use absolute path for the bots, then still launch them from inside their own directory. This should work for every case?

**Comment by ghost** [comment]
With LZ I create a link in the working directory (the GRP directory) to the weights file elsewhere and then the parameters is `--weights weights`. In the Polish documentation I wrote that for AQ and LZ the reference location is resolved to the command's path when the path (any) is provided or `pwd` otherwise. That's how I understand your code. I'm a Python beginner though... I've not tested AQ yet.

**Pull request merged**
